### ISSUE TITLE
WISH: triple quotes and raw strings like in Python

### ISSUE THREAD

**Issue by mgirlich** [HenrikBengtsson/Wishlist-for-R#106]
**triple quotes**
They allow using single and double quotes in a string without escaping them. This makes some strings  (e.g. SQL queries) so much more readable, e.g. writing

```
"""Sammy says, "The balloon's color is red." """
```

instead of

```
"Sammy says, \"The balloon's color is red.\" "
```

is much nicer.

**raw strings**
Characters prefaced by `\` are not interpreted as special characters e.g. paths on Windows work nicer

```
r'C:\some\name'
```

or less escaping in writing system commands.

I really miss these two features from Python.

**Comment by HenrikBengtsson** [comment]
I think we can close this.  From the R devel (to become R 4.0.0) [NEWS](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html):

> * R now provides a syntax for specifying raw character constants similar to the one used in C++: r"(...)" with ... any character sequence, except that it must not contain the closing sequence )". This makes it easier to write strings that contain backslashes or both single and double quotes. For more details see ?Quotes. 

Examples:

```r
> s <- r"(Sammy says, "The balloon's color is red.")"
> s
[1] "Sammy says, \"The balloon's color is red.\""
> cat(s)
Sammy says, "The balloon's color is red."
>
```

and

```r
> t <- r"(C:\some\name)"
> t
[1] "C:\\some\\name"
> cat(t)
C:\some\name
>
```

It also works with `r"{ ... }"` and `r"[ ... ]"`.

**Comment by mgirlich** [comment]
Awesome! Thanks a lot for the info.
