### ISSUE TITLE
R process within Rstudio does not inherit env variables (linux)

### ISSUE THREAD

**Issue by rsettlage** [HenrikBengtsson/Wishlist-for-R#117]
In Rstudio, at R prompt, `system("env | grep SLURM")` should get a list of env variables (if launched as a slurm job), others as appropriate.

**Comment by HenrikBengtsson** [comment]
I think this one is better asked over at RStudio's forums.  They'll be much better suited to help you out - hopefully they'll also have an answer. 

PS. This tracker is for core R features and oddities.  The idea is that they can be vetted and matured here before brought upstream to R's Bugzilla or the R-devel list.
