### ISSUE TITLE
bug in setting `warnPartialMatchDollar`? 

### ISSUE THREAD

**Issue by ijlyttle** [HenrikBengtsson/Wishlist-for-R#134]
I thought I might try this out here first, amongst friends :)

I think this is a bug but I'm not certain. My use case is to set this using `withr::local_options()`, but it wasn't getting set back as I would expect.

My reprex, using R 4.2.0:

``` r
# expected
getOption("warnPartialMatchDollar")
#> NULL
tmp <- mtcars$mp

# also expected
options(warnPartialMatchDollar = TRUE)
tmp <- mtcars$mp
#> Warning in mtcars$mp: partial match of 'mp' to 'mpg'

# *not* expected
options(warnPartialMatchDollar = NULL)
tmp <- mtcars$mp
#> Warning in mtcars$mp: partial match of 'mp' to 'mpg'

# expected
options(warnPartialMatchDollar = FALSE)
tmp <- mtcars$mp

# expected
options(warnPartialMatchDollar = NULL)
tmp <- mtcars$mp
```

<sup>Created on 2022-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Am I missing something?

**Comment by HenrikBengtsson** [comment]
Same behavior for the other `warnPartial...` options?

**Comment by ijlyttle** [comment]
Looks like it...

## `warnPartialMatchArgs`

``` r
# expected
getOption("warnPartialMatchArgs")
#> NULL
tmp <- subset(mtcars, sel = mpg)

# also expected
options(warnPartialMatchArgs = TRUE)
tmp <- subset(mtcars, sel = mpg)
#> Warning in subset.data.frame(mtcars, sel = mpg): partial argument match of 'sel'
#> to 'select'

# *not* expected
options(warnPartialMatchArgs = NULL)
tmp <- subset(mtcars, sel = mpg)
#> Warning in subset.data.frame(mtcars, sel = mpg): partial argument match of 'sel'
#> to 'select'

# expected
options(warnPartialMatchArgs = FALSE)
tmp <- subset(mtcars, sel = mpg)

# expected
options(warnPartialMatchArgs = NULL)
tmp <- subset(mtcars, sel = mpg)
```

<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

## `warnPartialMatchAttr`

``` r
# expected
getOption("warnPartialMatchAttr")
#> NULL
tmp <- attr(mtcars, "name")

# also expected
options(warnPartialMatchAttr = TRUE)
tmp <- attr(mtcars, "name")
#> Warning in attr(mtcars, "name"): partial match of 'name' to 'names'

# *not* expected
options(warnPartialMatchAttr = NULL)
tmp <- attr(mtcars, "name")
#> Warning in attr(mtcars, "name"): partial match of 'name' to 'names'

# expected
options(warnPartialMatchAttr = FALSE)
tmp <- attr(mtcars, "name")

# expected
options(warnPartialMatchAttr = NULL)
tmp <- attr(mtcars, "name")
```

<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by HenrikBengtsson** [comment]
I think a base-R argument for fixing this is that it's not possible to reliably query the internal state by looking at `getOption("warnPartialMatchDollar")`, because if the value is `NULL`, it's like Schrödinger's Cat.

It could be that there are other R options with the same "misfeature", i.e. setting the option to `NULL` changes the value, but not the underlying behavior.

**Comment by ijlyttle** [comment]
@HenrikBengtsson - thanks! 

I agree that `NULL` should be deterministic rather than sticky.

I have requested an account on Bugzilla, we'll see what happens!

**Comment by ijlyttle** [comment]
Just to link this with the bugzilla report: https://bugs.r-project.org/show_bug.cgi?id=18372

**Comment by ijlyttle** [comment]
Now fixed in R-devel r83370 (https://github.com/wch/r-source/commit/593df7418e92a771904da730ace2dcb8bf5d221e).

**Comment by HenrikBengtsson** [comment]
Excellent.

```r
$ R --vanilla

R Under development (unstable) (2022-11-21 r83370) -- "Unsuffered Consequences"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
...

> oopt <- options(warnPartialMatchDollar = TRUE)
> str(oopt)
List of 1
 $ warnPartialMatchDollar: logi FALSE
```

```r
$ R --quiet --vanilla

> options(warnPartialMatchDollar = TRUE)
> tmp <- mtcars$mp
Warning message:
In mtcars$mp : partial match of 'mp' to 'mpg'
> options(warnPartialMatchDollar = NULL)
Error in options(warnPartialMatchDollar = NULL) : 
  option 'warnPartialMatchDollar' cannot be deleted
```

**Comment by ijlyttle** [comment]
@HenrikBengtsson just a quick note to say thanks for nudging this issue along with R-Core!

Also, of course, thanks for hosting this repo as a place to work ideas out!
