### ISSUE TITLE
Why not use moderne alternative?

### ISSUE THREAD

**Issue by gagarine** [HenrikBengtsson/Wishlist-for-R#87]
I (honestly) don't understand why you want to try to improve an old language when you have so many good modern alternative from [Julia](https://julialang.org/) to Python with ready to use distribution like [anaconda](https://www.anaconda.com/) and environment like [spyder](https://www.spyder-ide.org/) or [juno](http://junolab.org/) .

**Comment by jangorecki** [comment]
Python isn't an old language too? Funny you mentioned anaconda, it always gives me more problems than it solves. In R we have built-in libraries (basically any directory) we can easily switch, and we don't need any extra software for that. Julia is definitely worth to look into, while it is modern, and well designed, it doesn't seems to be mature enough.

**Comment by gagarine** [comment]
@jangorecki I just didn't see the point to invest massive energy to improve R. Especially if those changes introduce incompatibility (ie. python 2 to python 3 migration was painful).
