### ISSUE TITLE
WISH: Make it possible to reset all options (some can't right now)

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/Wishlist-for-R#88]
Make it possible to reset _all_ options as they appear in a fresh R session, e.g.

```r
$ R --vanilla

## Option 'warnPartialMatchArgs' does not exist
> "warnPartialMatchArgs" %in% names(options())
[1] FALSE
> getOption("warnPartialMatchArgs")
NULL

## Setting option ...
> options(warnPartialMatchArgs = FALSE)
> getOption("warnPartialMatchArgs")
[1] FALSE

## ... but we cannot undo/reset it to the original state
> options(warnPartialMatchArgs = NULL)
Error in options(warnPartialMatchArgs = NULL) : 
  invalid value for 'warnPartialMatchArgs'
```

**Comment by mmaechler** [comment]
This was discussed ca one year ago notably as part of your (and others) performance improvement suggestion for `getOption()`  on bugzilla:  https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17394
.. some of the discussion "of course" became offline I think.
We had agreed there that  an option that is `NULL`  and a non-existing option should behave equivalently in all relevant aspects, i.e., when using `getOptions()` when doing the equivalent in R's internal C code.   Consequently, if you compare versions of `options()` you should remove `NULL` entries before the comparison and declare equality when the versions are the same *after* eliminating `NULL` components.

**Comment by HenrikBengtsson** [comment]
Thxs, but I'm not sure I understand your comment.  To clarify the issue, how can I achieve something like:
```r
foo <- function() {
  ## Temporary use factory 'warnPartialMatchArgs' settings
  oopts <- options(warnPartialMatchArgs = NULL)  # throws an error
  on.exit(options(oopts))
  ...
}
```
Note that there's nothing in the R API that allows me to infer that the factory setting corresponds to `warnPartialMatchArgs = FALSE`.  That information is only available in the docs.

**Comment by HenrikBengtsson** [comment]
UPDATE 2019-03-26: R devel [r76270](https://github.com/wch/r-source/commit/be73c1ad8cb6e70a46423dd27d4d2ab298386668) ("Allow deletion of options checked on assignment, unless they were set during R startup (R initialization or common paths of system profile).") appears to address this:

```r
$ R
R Under development (unstable) (2019-03-26 r76271) -- "Unsuffered Consequences"
[...]
> "warnPartialMatchArgs" %in% names(options())
[1] FALSE
> getOption("warnPartialMatchArgs")
NULL
> options(warnPartialMatchArgs = FALSE)
> getOption("warnPartialMatchArgs")
[1] FALSE
> options(warnPartialMatchArgs = NULL)
> getOption("warnPartialMatchArgs")
NULL
> 
```

**Comment by HenrikBengtsson** [comment]
Thanks @kalibera for fixing this.
